/*
 * generated by Xtext
 */
package de.michaelpoetz.backendgenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BackendGeneratorUiModule extends de.michaelpoetz.backendgenerator.ui.AbstractBackendGeneratorUiModule {
	public BackendGeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
