/*
 * generated by Xtext
 */
package de.michaelpoetz.backendgenerator.ui.contentassist

import de.michaelpoetz.backendgenerator.ui.contentassist.AbstractBackendGeneratorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BackendGeneratorProposalProvider extends AbstractBackendGeneratorProposalProvider {
}
