/*
* generated by Xtext
*/
package de.michaelpoetz.backendgenerator;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BackendGeneratorStandaloneSetup extends BackendGeneratorStandaloneSetupGenerated{

	public static void doSetup() {
		new BackendGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

