/*
 * generated by Xtext
 */
package de.michaelpoetz.backendgenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BackendGeneratorRuntimeModule extends de.michaelpoetz.backendgenerator.AbstractBackendGeneratorRuntimeModule {

}
